"""initial schema

Revision ID: e9a0e064023b
Revises: 
Create Date: 2026-05-11 18:40:51.046168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a0e064023b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('candidate', 'counselor', 'admin', name='user_role'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'paid', name='user_plan'), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('system_prompt_text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_is_active'), ['is_active'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('draft', 'queued', 'running', 'success', 'error', 'timeout', name='analysis_status'), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('counselor_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('counselor_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counselor_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counselor_notes_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counselor_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counselor_notes_analysis_id'))

    op.drop_table('counselor_notes')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_share_token'))

    op.drop_table('analyses')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_is_active'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
