"""nullable user_id on analyses

Revision ID: fd6e96d0d77c
Revises: e9a0e064023b
Create Date: 2026-05-11 19:58:02.909441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd6e96d0d77c'
down_revision = 'e9a0e064023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False)

    # ### end Alembic commands ###
